version: '3'
services:
  db:
    build: ./database
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my-network
    # backend will wait till db is ready
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    networks:
      - my-network
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  db_data:

networks:
  my-network:
